Repository FatecCoderHood/GSW_API, pull requests merged in 2024-10, with the labels that each got.

#18 A3F-41 [Doc]: Criar template padrão de commit message
  .gitmessage.txt
Labels: documentation

#19 A3F-35 [Frontend] Implementar filtros de pesquisa por tags
  Front/gsw-api/src/components/HelloWorld.vue
  Front/gsw-api/src/components/Settings.vue
  server/gsw_api/src/main/java/gsw_api/gsw_api/dto/FiltroNoticia.java
  server/gsw_api/src/main/java/gsw_api/gsw_api/service/NoticiaService.java
  server/gsw_api/src/main/resources/application-dev.properties
Labels: functionality

#20 A3F-42 [Doc]: Atualização periódica do gráfico burndown
  README.md
  documentacao/Burndown/sprint1/burndown_sprint1.png
  documentacao/Burndown/sprint2/burndown_sprint2_2024-10-13.png
  documentacao/regras_de_negócios.md
Labels: documentation

#23 A3F-23 [Front]: Update Node Modules
  Front/gsw-api/package-lock.json
  Front/gsw-api/package.json
Labels: functionality

#25 A3F-42 [Doc]: Atualização periódica do gráfico burndown
  README.md
  documentacao/Burndown/sprint2/burndown_sprint2_2024-10-14.png
Labels: documentation

#26 A3F-30 [Backend] : Garantir que não tenha tags duplicadas
  back/gsw-api/src/main/java/gsw_api/gsw_api/controller/TagController.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/dao/TagRepository.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/gws.sql
  back/gsw-api/src/main/java/gsw_api/gsw_api/model/Tag.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/TagService.java
Labels: functionality

#28 A3F-32 [Backend]: Desenvolver serviço para coleta de informações de sites de notícias.
  back/gsw-api/src/main/java/gsw_api/gsw_api/gws.sql
Labels: enhancement

#29 A3F-42 [Doc]: Atualização periódica do gráfico burndown
  README.md
  documentacao/Burndown/sprint2/burndown_sprint2_2024-10-17.png
Labels: documentation

#31 A3F-32 [Backend]: Desenvolver serviço para coleta de informações de sites de notícias.
  back/gsw-api/src/main/java/gsw_api/gsw_api/gws.sql
Labels: bug

#34 3F-38 [Backend] Banco: Regionalidade de tags
  README.md
  back/gsw-api/src/main/java/gsw_api/gsw_api/gws.sql
Labels: functionality

#35 A3F-34 [Backend]: Garantir que as notícias duplicadas sejam identificadas e evitadas no processo de armazenamento.
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/WebScrapingService.java
Labels: enhancement

#36 A3F-29 [Backend]: Garantir que não tenha cadastro duplicados de portais.
  back/gsw-api/src/main/java/gsw_api/gsw_api/dao/PortalNoticiaRepository.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/PortalNoticiaService.java
Labels: enhancement

#37 A3F-42 [Doc]: Atualização periódica do gráfico burndown
  README.md
  documentacao/Burndown/sprint2/burndown_sprint2_2024-10-20.png
Labels: documentation

#38 A3F-23 [Doc]: Procedimento de Build e Execução
  README.md
Labels: documentation

#39 A3F-32 [Frontend]: Desenvolver serviço para coleta de informações de …
  Front/gsw-api/src/components/News.vue
Labels: enhancement, functionality

#40 A3F-40 [Frontend]: Cadastro de APIs
  Front/gsw-api/src/components/Sources.vue
  back/gsw-api/src/main/java/gsw_api/gsw_api/controller/ApiController.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/model/Api.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/ApiService.java
Labels: functionality

#45 A3F-42 [Doc]: Atualização periódica do gráfico burndown
  README.md
Labels: documentation

#46 A3F-40 [Frontend] Edição e exclusão de tags
  back/gsw-api/src/main/java/gsw_api/gsw_api/controller/PortalApiController.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/controller/TagController.java
Labels: bug, enhancement

#52 A3F-56 [Bug]: Tag : Validação
  Front/gsw-api/src/components/Settings.vue
Labels: bug
