Repository FatecCoderHood/GSW_API, pull requests merged in 2024-12, with the labels that each got.

#97 A3F-82 [Backend] Indicação por tag relacionada
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/ApiScrapingService.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/SchedulerApiService.java
Labels: enhancement

#104 A3F-23 [Backend]: Correção na edição de Tag como Source
  back/gsw-api/src/main/java/gsw_api/gsw_api/model/Api.java
Labels: bug, fix

#105 A3F-83 Atualização do burndown
  README.md
  documentacao/Burndown/sprint4/burndown_sprint4_2024-12-01.png
Labels: documentation

#107 A3F - 80 [Doc] Manual de usuário
  README.md
Labels: documentation
