Repository FatecCoderHood/GSW_API, pull requests merged in 2024-11, with the labels that each got.

#54 <A3F-69> [Frontend] Aviso de confirmação cadastro
  Front/gsw-api/src/components/Sources.vue
Labels: functionality

#60 A3F-49 [Frontend]: Campo de payload
  Front/gsw-api/src/components/Sources.vue
Labels: enhancement

#61 A3F-62 [Doc] Atualização regular do burndown.
  README.md
  documentacao/Burndown/sprint3/burndown_sprint3_2024-09-31.png
  documentacao/Burndown/sprint3/burndown_sprint3_2024-11-03.png
  documentacao/Burndown/sprint3/burndown_sprint3_2024-11-03_novo.png
Labels: documentation

#62 A3F-37 [Backend] API/Servidor: Regionalidade de tags.
  back/gsw-api/src/main/java/gsw_api/gsw_api/config/AppConfig.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/dao/NoticiaRepository.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/dao/TagRepository.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/gws.sql
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/NoticiaService.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/SinonimoService.java
  back/gsw-api/src/main/resources/application-dev.properties
Labels: functionality

#63 A3F-68[Frontend]: Aviso de duplicação de cadastro.
  Front/gsw-api/src/components/Sources.vue
Labels: enhancement

#64 A3F-57[Frontend]: Tag: Aviso de cadastro.
  Front/gsw-api/src/components/Settings.vue
Labels: enhancement

#65 A3F-65[Frontend]: Implementar Botão Webscraping.
  Front/gsw-api/src/components/Settings.vue
Labels: enhancement

#66 A3F-60 [Backend] API: Implementação de serviço de scraping.
  Front/gsw-api/src/components/News.vue
  back/gsw-api/src/main/java/gsw_api/gsw_api/GswApiApplication.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/config/AppConfig.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/controller/NoticiaController.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/dao/NoticiaRepository.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/model/Api.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/model/Noticia.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/ApiScrapingService.java
  back/gsw-api/src/main/resources/application-dev.properties
Labels: functionality

#67 A3F-62 [Doc] Atualização regular do burndown.
  README.md
  documentacao/Burndown/sprint3/burndown_sprint3_2024-11-04.png
Labels: documentation

#68 A3f-45 [Backend]: Periodicidade Scraping.
  back/gsw-api/src/main/java/gsw_api/gsw_api/dao/PortalNoticiaRepository.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/dto/DadosPortalNoticia.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/gws.sql
  back/gsw-api/src/main/java/gsw_api/gsw_api/model/PortalNoticia.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/PortalNoticiaService.java
Labels: enhancement

#77 A3F-45 [Backend] Notícia/API: Periodicidade Scraping.
  back/gsw-api/src/main/java/gsw_api/gsw_api/GswApiApplication.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/model/Noticia.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/PortalNoticiaService.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/SchedulerService.java
Labels: functionality

#71 A3F-70 [Feature] Vincular Tag à Notícia
  Front/gsw-api/src/components/ColorPicker.vue
  Front/gsw-api/src/components/News.vue
  Front/gsw-api/src/components/Settings.vue
  Front/gsw-api/src/components/TagList.vue
  back/gsw-api/src/main/java/gsw_api/gsw_api/config/WebConfig.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/controller/NoticiaController.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/controller/TagController.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/dao/TagRepository.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/dto/DadosTag.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/model/Noticia.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/model/Tag.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/NoticiaService.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/TagService.java
Labels: functionality

#76 A3F-48 [Backend] Escopo Webscraping
  back/gsw-api/src/main/java/gsw_api/gsw_api/gws.sql
Labels: enhancement

#78 A3F-62 [Doc] Atualização regular do burndown.
  README.md
  documentacao/Burndown/sprint3/burndown_sprint3_2024-11-09.png
  documentacao/Burndown/sprint3/burndown_sprint3_2024-11-10.png
Labels: documentation

#79 Entrega sprint 3
  Front/gsw-api/src/components/ColorPicker.vue
  Front/gsw-api/src/components/News.vue
  Front/gsw-api/src/components/Settings.vue
  Front/gsw-api/src/components/Sources.vue
  Front/gsw-api/src/components/TagList.vue
  README.md
  back/gsw-api/src/main/java/gsw_api/gsw_api/GswApiApplication.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/config/AppConfig.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/config/WebConfig.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/controller/ApiController.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/controller/NoticiaController.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/controller/TagController.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/dao/ApiRepository.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/dao/NoticiaRepository.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/dao/PortalNoticiaRepository.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/dao/TagRepository.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/dto/DadosPortalNoticia.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/dto/DadosTag.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/dto/SinonimoResponse.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/gws.sql
  back/gsw-api/src/main/java/gsw_api/gsw_api/model/Api.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/model/Noticia.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/model/PortalNoticia.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/model/Tag.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/ApiScrapingService.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/ApiService.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/NoticiaService.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/PortalNoticiaService.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/SchedulerService.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/SinonimoService.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/TagService.java
  back/gsw-api/src/main/resources/application-dev.properties
  documentacao/Burndown/sprint3/burndown_sprint3_2024-09-31.png
  documentacao/Burndown/sprint3/burndown_sprint3_2024-11-03.png
  documentacao/Burndown/sprint3/burndown_sprint3_2024-11-03_novo.png
  documentacao/Burndown/sprint3/burndown_sprint3_2024-11-04.png
  documentacao/Burndown/sprint3/burndown_sprint3_2024-11-06.png
  documentacao/Burndown/sprint3/burndown_sprint3_2024-11-09.png
  documentacao/Burndown/sprint3/burndown_sprint3_2024-11-10.png
Labels: release

#80 <A3F-68>[Frontend] Aviso de duplicação de Fontes.
  Front/gsw-api/src/components/Sources.vue
Labels: bug

#81 A3F23 - [HotFix] Exclusão de fonte
  Front/gsw-api/src/components/Sources.vue
  back/gsw-api/src/main/java/gsw_api/gsw_api/controller/ApiController.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/PortalNoticiaService.java
Labels: fix

#83 A3F-23 [HotFix] Seleção de portais no config do webscraping
  Front/gsw-api/src/components/Settings.vue
Labels: fix

#84 A3F-23 [HotFix] Filtro de Tag
  Front/gsw-api/src/components/News.vue
  Front/gsw-api/src/components/Settings.vue
Labels: enhancement, functionality, fix

#86 A3F-80[Doc]: Manual de usuário
  documentacao/Manual/imagem_msql_02.webp
  documentacao/Manual/imagem_msql_03.webp
  documentacao/Manual/imagem_msql_04.webp
  documentacao/Manual/imagem_msql_05.webp
  documentacao/Manual/imagem_msql_06.webp
  documentacao/Manual/imagem_msql_07.webp
  documentacao/Manual/imagem_msql_08.webp
  documentacao/Manual/imagem_msql_09.png
  documentacao/Manual/manual_imag_01.png.png
  documentacao/Manual/manual_imag_02.png
Labels: documentation

#93 A3F-76 [Feature]: Periodicidade para API
  back/gsw-api/src/main/java/gsw_api/gsw_api/dao/ApiRepository.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/ApiService.java
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/SchedulerApiService.java
Labels: functionality

#94 A3F-81 [Backend] Lógica para incluir mais api
  back/gsw-api/src/main/java/gsw_api/gsw_api/gws.sql
  back/gsw-api/src/main/java/gsw_api/gsw_api/service/ApiScrapingService.java
Labels: enhancement

#96 <A3F-57>[Bug]:Tag: Aviso de cadastro.
  Front/gsw-api/src/components/Settings.vue
Labels: bug
